#NeXTQuarry v1.1.0 - by BeMacized - http://www.NeXTBattle.Net/

# -- CONFIG -- 

# -- QUARRY OPTIONS --
#Private Quaries: If set to true, players can't mine quarries of others. Only their own. The nextquarry.admin permission node overrides this. OP status has the same effect.
private-quarries: true
#Ignore Blocks: All blocktypes in this list can't be mined by a quarry. IMPORTANT: Removing the liquids from this list, may lag or crash your server!
ignored-blocks:
- '7'
- '49'
- '9'
- '11'
- '8'
- '10'

# -- PLUGIN OPTIONS --
#Auto Update: Makes sure the plugin updates automatically when there's an update available.
auto-update: true
#Update Notifications: Gives you a notification when there's a new update available.
#NOTE: Only works when auto update is turned off!
update-notify: false

# -- ANTI-LAG OPTIONS --
#Continue when unloaded: If set to false, quarries will not do anything when they are in an unloaded chunk.
continue-when-unloaded: false
#Continue when offline: If set to false, quarries will not do anything when their owner is offline.
continue-when-offline: false

# -- MISCELLANEOUS OPTIONS --
#Dev join message: Shows a custom join message for any developer who joins. Please leave this on.
dev-join-message: true
#Send usage data: Sends anonymous usage data about the plugin for statistics to mcstats.org
#Please leave this on, as it gives us an idea on how much our plugin is used. No personal data is sent.
send-usage-data: true


